### ISSUE TITLE
sql2gorm是哪个项目

### ISSUE THREAD

**Issue by guoxk** [miaogaolin/sql2ent#2]
大佬，之前那个sql2gorm工具挺好用，因为网站关闭了，所以找到git没发现那个项目的地址。

**Comment by miaogaolin** [comment]
> 大佬，之前那个sql2gorm工具挺好用，因为网站关闭了，所以找到git没发现那个项目的地址。
https://github.com/miaogaolin/gotl 这是工具的 api 接口项目，启动起来直接访问
![image](https://user-images.githubusercontent.com/57740293/155294060-bd18eecc-36fa-4521-a440-4a3c1c0444fc.png)

**Comment by guoxk** [comment]
感谢🙏

**Comment by miaogaolin** [comment]
https://printlove.cn 网站又恢复了，可以正常使用了
