### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by star-with-me** [miaogaolin/sql2ent#3]
作者你好，非常感谢你提供这么棒的生产力工具
![image](https://user-images.githubusercontent.com/90305218/157184036-3d22565b-1c8e-4e48-ba76-b689b2e81c27.png)

是否可以考虑更全面一点呢，比如增加SQL转MongoDB等

**Comment by miaogaolin** [comment]
mongdb 我不太使用，下来有时间可以研究下，或者你也可以提 pr
https://github.com/miaogaolin/gotl
