### ISSUE TITLE
生成mysql ddl时报错 unsupported database error 21

### ISSUE THREAD

**Issue by houko** [miaogaolin/sql2ent#6]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/12625278/172752001-12fa7287-36eb-48e1-892a-c60581832ab0.png">

**Comment by houko** [comment]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/12625278/172752441-0fda0d60-d4c5-47b8-b69a-6098e556c6b2.png">
我又试了下，把表注释了只留一个表的话是可以成功的，应该是我的表里有啥毛病导致转换失败。

出错的表DDL
```
CREATE TABLE `purchase_detail` (
      `id` bigint(20) NOT NULL COMMENT 'purchase id',
      `ver` varchar(6) COLLATE ascii_bin NOT NULL COMMENT 'the version of the data',
      `format` varchar(24) COLLATE ascii_bin NOT NULL COMMENT 'the format to which the data is encoded',
      `data` blob NOT NULL COMMENT 'encoded data',
      PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin;
```

**Comment by miaogaolin** [comment]
能否提供下你的sql

**Comment by houko** [comment]
不是贴在上面么

**Comment by miaogaolin** [comment]
不支持blob

**Comment by houko** [comment]
> 不支持blob

原来如此，谢谢

**Comment by miaogaolin** [comment]
重新安装试试

**Comment by houko** [comment]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/12625278/173537116-441d737d-b10d-486b-83c3-298d58b468a9.png">
又出现新的错误了
